package com.example.resumeanalyzer.service;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

@Service
public class PdfService {

    public byte[] generateResumeReport(
            String atsScore,
            String matchScore,
            String summary,
            String strengths,
            String gaps,
            String suggestedJobs) {

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        PdfWriter writer = new PdfWriter(outputStream);
        PdfDocument pdfDocument = new PdfDocument(writer);
        Document document = new Document(pdfDocument);

        document.add(new Paragraph("===================================="));
        document.add(new Paragraph("          AI RESUME ANALYZER"));
        document.add(new Paragraph("          Resume Report"));
        document.add(new Paragraph("===================================="));

        document.add(new Paragraph(""));

        document.add(new Paragraph("ATS Score : " + atsScore));
        document.add(new Paragraph("Match Score : " + matchScore));

        document.add(new Paragraph(""));

        document.add(new Paragraph("SUMMARY"));
        document.add(new Paragraph(summary));

        document.add(new Paragraph(""));

        document.add(new Paragraph("STRENGTHS"));
        document.add(new Paragraph(strengths));

        document.add(new Paragraph(""));

        document.add(new Paragraph("GAPS"));
        document.add(new Paragraph(gaps));

        document.add(new Paragraph(""));

        document.add(new Paragraph("SUGGESTED JOBS"));
        document.add(new Paragraph(suggestedJobs));

        document.add(new Paragraph(""));
        document.add(new Paragraph("Generated by AI Resume Analyzer"));

        document.close();

        return outputStream.toByteArray();
    }
}